### ISSUE TITLE
Android 11 2K/4K Video-Support

### ISSUE THREAD

**Issue by Netroxen** [HorizonCamera/HorizonSDK-Android#3]
Android Version: 11
Device: SM-G985F / Galaxy S20+

Greetings

This is more a feature request rather than an issue with the app itself. I see that on iOS the SDK supports recording video at 2k/4k resolution using the "Crisp" mode. Is there a technical limitation to the Android API that is preventing this same functionality being usable on Android devices ..?

At least, on the Galaxy S20+ there are multiple rear cameras, including a wide angle lens which is obviously more practical for recording horizon leveled videos.

Edit: I have read the FAQ regarding live video processing. Is this a compatability problem, I find it pretty strange that the software would be limited to 1080p on a device which can record 8k video.

**Comment by Petrakeas** [comment]
Yes, the reason is that we use the first Camera API, which unlike Camera API 2, does not expose these resolutions.

**Comment by Netroxen** [comment]
It's a shame because 1080p video somewhat negates the usefulness of the app. Modes such as "Rotate" already crop the video in to negate the zoom effect, which makes the resulting video sub-par for vlogging or content creation. For clarification, I did purchase the Pro version of the app to support the project.

Is there a chance to deprecate the old API support and compatability, in favour of supporting newer devices that offer far more hardware capability ..?

I'm a backend engineer, so Android development is out of my water. But surely there's a medium where progressive support could be implemented as a start ..?

Thanks for the fast reply!

**Comment by Petrakeas** [comment]
We are aware of the advantages of moving to the newer API, but this will require a rewrite of our processing pipeline. It is on our future plans.

I am closing this issue. For any more assistance regarding the app, please contact us from within the app.
